### ISSUE TITLE
Scrollbar Shadow should have position absolute by default

### ISSUE THREAD

**Issue by yairEO** [open-amdocs/webrix#111]
Currently, [`Shadow.jsx`](https://github.com/open-amdocs/webrix/blob/master/src/components/Scrollable/components/Shadow/Shadow.jsx) does not come with [CSS](https://github.com/open-amdocs/webrix/blob/master/src/components/Scrollable/components/Shadow/Shadow.scss) that has `position`

```jsx
<Scrollable.Shadow>
    <Scrollable>
        ...
    </Scrollable>
</Scrollable.Shadow>
```

And so, whoever is using the Scrollable Shadow needs to write that part in their own CSS (in their app):

```CSS
.scroll-shadow {
    position: absolute;
    inset: 0;
    pointer-events: none;
  }
```

And it begs the question why does the above CSS not come out-of-the-box inside the `<Shadow>` component SCSS file.
